### ISSUE TITLE
something question about the code

### ISSUE THREAD

**Issue by JiaheXu** [alexspirou/ROS_Melodic_Qt_GUI_Template#1]
in mainwindow.cpp  there is a `connect(timer, SIGNAL(timeout()),this,SLOT(optical_encoder_measurements()));`
Could you please tell me what optical_encoder_measurements() do? Is it a system function? I cannot see it else where in the package. I tried delete it, the code still could run. Please reply, thanks!

**Comment by alexspirou** [comment]
No it's a function of mine. You don't need it. I will remove it.
